# Site settings
title:          Alkaid's Blog
description:    "Minimal Jekyll theme for storytellers"
url:            'https://ifoz.net'
baseurl:        ''

future:         true
# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Alkaid
  url:          https://ifoz.net
  email:        alkaid.waong@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

remote_theme: chesterhow/tale
# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         ifozalkaid
comments: true