# Site settings
title:          Alkaid's Blog
description:    "物来顺应，未来不迎，当时不杂，既往不恋。"
url:            'https://blog.ifoz.net'
baseurl:        ''

future:         true
# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Alkaid
  url:          https://blog.ifoz.net
  email:        alkaid.waong@foxmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

remote_theme: chesterhow/tale
# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# sdisqus:            ifoz-net
shortname:         Alkaid
comments:         false